package l36try2;

import java.io.IOException;
import java.text.ParseException;

public class Application {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		Test test = new Test();

		/*
		 * try { test.run(); } catch (IOException e) { // TODO Auto-generated
		 * catch block e.printStackTrace(); } catch (ParseException e) {
		 * System.out.println("There is a parse exception."); }
		 */

		/*
		try {
			test.run();
		} catch (IOException | ParseException e) {

			System.out.println("There is a parse exception");
		}
		*/
		
		try {
			test.run();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		

	}

}
